#!/bin/zsh

mkdir -p ~/.config/nvim/{plugin,after,lua}
mkdir -p ~/.config/nvim/after/plugin

#mkdir -p ~/.config/nvim/plugin
#mkdir -p ~/.config/nvim/after/plugin
#mkdir -p ~/.config/nvim/lua

#link all
#pushd ~/acelaya77/configs/
pushd ~/repos/configs/

for f in `find * -regex ".*\.vim$\|.*\.lua$"`; do
    rm -rf ~/.config/nvim/$f
    #ln -vs ~/acelaya77/configs/$f ~/.config/nvim/$f
    ln -vs ~/repos/configs/$f ~/.config/nvim/$f
    echo "$f"
done

popd 


